//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniatureBottleDesktopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottle
    {
        public int ID { get; set; }
        public string Shelf { get; set; }
        public string Name { get; set; }
        public string Shape { get; set; }
        public string Material { get; set; }
        public int Age { get; set; }
        public string Note { get; set; }
        public byte[] BottleImage { get; set; }
    }
}
