//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniatureBottleDesktopClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class BottleContent
    {
        public int BottleID { get; set; }
        public string Alcohol { get; set; }
        public string AlcoholType { get; set; }
        public string BottleContent1 { get; set; }
    
        public virtual Origin Origin { get; set; }
    }
}
